# -*- coding: utf-8 -*-
"""cam-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvEbYljHaZRmARGlGX2wLENClfq5XcI1
"""

!pip install -q ultralytics

from google.colab import drive
drive.mount('/content/drive')

import os

for root, dirs, files in os.walk("/content/drive/MyDrive/Artic/Artic-cam2.zip"):
    for file in files:
        if file.endswith('.zip'):
            print(os.path.join(root, file))

import zipfile
import os

# Path to your ZIP file
zip_path = "/content/drive/MyDrive/Artic/Artic-cam2.zip"

# Folder where the dataset will be extracted
extract_path = "/content/dataset"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

!ls /content/dataset

!pip install -q ultralytics

from ultralytics import YOLO

with open('/content/dataset/Artic-cam2/data_yolov26.yaml') as f:
    print(f.read())

yaml_content = """
path: /content/dataset/Artic-cam2
train: train/images
val: valid/images
test: test/images

names:
  0: cotton_bale
"""

with open('/content/dataset/Artic-cam2/data_yolov26.yaml', 'w') as f:
    f.write(yaml_content)

from ultralytics import YOLO

# Load your custom pretrained checkpoint
model = YOLO("/content/drive/MyDrive/Artic/Artic-cam2.pt")

results = model.train(
    data="/content/dataset/Artic-cam2/data_yolov26.yaml",
    epochs=25,               # Reduced from 100/50; 20-30 epochs is the sweet spot for ~300 images
    imgsz=640,
    batch=8,
    optimizer="AdamW",
    lr0=0.0001,              # Conservative LR to avoid overshooting in small epoch counts
    lrf=0.1,                 # Higher end LR ratio (0.0001 * 0.1 = 0.00001) for smoother decay
    warmup_epochs=1.0,       # Shortened to 1 epoch (~40 steps) to match short run

    # --- Freeze & Regularization ---
    freeze=10,               # Protects backbone weights
    weight_decay=0.005,
    dropout=0.1,

    # --- Data Augmentations ---
    mosaic=0.3,              # Minimal mosaic to prevent feature distortion on small runs
    mixup=0.0,
    hsv_h=0.015,
    hsv_s=0.5,
    hsv_v=0.4,
    degrees=10.0,
    fliplr=0.5,

    # --- Early Stopping & Saving ---
    patience=5,              # Lowered patience to stop immediately if validation loss spikes
    device=0,
    project="/content/drive/MyDrive/Yolo_Model-artic",
    name="ARTIC_CAM2",
    exist_ok=True,
    save=True,
    save_period=5
)