# -*- coding: utf-8 -*-
"""cam-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvEbYljHaZRmARGlGX2wLENClfq5XcI1
"""

!pip install -q ultralytics

from google.colab import drive
drive.mount('/content/drive')

import os

for root, dirs, files in os.walk("/content/drive/MyDrive/Merge-cam2.zip"):
    for file in files:
        if file.endswith('.zip'):
            print(os.path.join(root, file))

import zipfile
import os

# Path to your ZIP file
zip_path = "/content/drive/MyDrive/Merge-cam2.zip"

# Folder where the dataset will be extracted
extract_path = "/content/dataset"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

!ls /content/dataset

!pip install -q ultralytics

from ultralytics import YOLO

with open('/content/dataset/Merge-cam2/data.yaml') as f:
    print(f.read())

yaml_content = """
path: /content/dataset/Merge-cam2
train: train/images
val: valid/images
test: test/images

names:
  0: cotton_bale
"""

with open('/content/dataset/Merge-cam2/data.yaml', 'w') as f:
    f.write(yaml_content)

model = YOLO("yolo26m.pt")

model.train(
    data="/content/dataset/Merge-cam2/data.yaml",
    epochs=100,
    imgsz=640,
    batch=8,
    patience=20,
    cos_lr=True,
     project="/content/drive/MyDrive/TATA-2",
    name="TATA_cam2",
    exist_ok=True,

    save=True,
    save_period=10
)